version: '3.7'

services:
  api1: &api
    #image: docker.io/akitaonrails/rinhabackend-crystal:latest
    build: .
    hostname: api1
    environment:
      - SERVER_PORT=3001
      - SERVER_CONCURRENCY=25
    network_mode: "host"
    depends_on:
      database:
        condition: service_healthy
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.20GB'

  api2:
    <<: *api
    hostname: api2
    environment:
      - SERVER_PORT=3002
      - SERVER_CONCURRENCY=25
    depends_on:
      - api1

  nginx: # Load Balancer
    image: docker.io/nginx:alpine
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    network_mode: "host"
    depends_on:
      - api1
      - api2
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '0.40GB'

  database: # Banco de dados
    image: docker.io/postgres:alpine
    hostname: database
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    network_mode: "host"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    tmpfs:
      - /run
    healthcheck:
      test: [ "CMD-SHELL", "[ -r /var/run/postgresql/ready ] || ( pg_isready && touch /var/run/postgresql/ready)" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '2.0GB'

volumes:
  dbdata:
